# Generated by Django 5.0.6 on 2025-09-07 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("searching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerexperience",
            name="experience_categories",
            field=models.ManyToManyField(
                related_name="service_provider_experiences_categories",
                to="searching.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="serviceprovider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providerexperience",
            name="service_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider_experiences",
                to="accounts.serviceprovider",
            ),
        ),
    ]
