# Generated by Django 5.2.4 on 2025-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('service_seeker', 'Cliente'), ('service_provider', 'Proveedor')], max_length=20),
        ),
    ]
